include:
  - spring-boot-app/docker-compose.multi.yml
  - flask-app/docker-compose.multi.yml
  - gin-app/docker-compose.multi.yml
  - actix-web-app/docker-compose.multi.yml
  - next-app/docker-compose.multi.yml
